import type { DashboardData } from "@/types/dashboard"

// Mock data that simulates API responses
export const mockDashboardData: DashboardData = {
  creditCard: {
    id: "1",
    brand: "Vision UI",
    number: "7812 2139 0823 XXXX",
    validThru: "05/24",
    cvv: "09X",
    type: "mastercard",
  },
  creditBalance: {
    amount: 25215,
    currency: "$",
    billAndTaxes: {
      amount: -154.5,
      description: "Bill & Taxes",
      date: "Today, 16:36",
    },
  },
  invoices: [
    {
      id: "1",
      date: "March 01, 2020",
      invoiceNumber: "MS-415646",
      amount: 180,
      currency: "$",
      status: "paid",
    },
    {
      id: "2",
      date: "February 10, 2021",
      invoiceNumber: "RV-126749",
      amount: 250,
      currency: "$",
      status: "paid",
    },
    {
      id: "3",
      date: "April 05, 2020",
      invoiceNumber: "FB-212562",
      amount: 560,
      currency: "$",
      status: "paid",
    },
    {
      id: "4",
      date: "June 25, 2019",
      invoiceNumber: "QW-103578",
      amount: 120,
      currency: "$",
      status: "paid",
    },
    {
      id: "5",
      date: "March 01, 2019",
      invoiceNumber: "AR-803481",
      amount: 300,
      currency: "$",
      status: "paid",
    },
  ],
  paymentMethods: [
    {
      id: "1",
      brand: "Mastercard",
      number: "7812 2139 0823 XXXX",
      validThru: "05/24",
      cvv: "09X",
      type: "mastercard",
    },
    {
      id: "2",
      brand: "Visa",
      number: "7812 2139 0823 XXXX",
      validThru: "05/24",
      cvv: "09X",
      type: "visa",
    },
  ],
  billingInfo: [
    {
      id: "1",
      name: "Oliver Liam",
      companyName: "Viking Burrito",
      email: "oliver@burrito.com",
      vatNumber: "FRB1235476",
    },
    {
      id: "2",
      name: "Oliver Liam",
      companyName: "Viking Burrito",
      email: "oliver@burrito.com",
      vatNumber: "FRB1235476",
    },
    {
      id: "3",
      name: "Oliver Liam",
      companyName: "Viking Burrito",
      email: "oliver@burrito.com",
      vatNumber: "FRB1235476",
    },
  ],
  transactions: [
    {
      id: "1",
      company: "Netflix",
      date: "27 March 2020, at 12:30 PM",
      amount: 2500,
      currency: "$",
      status: "completed",
      type: "expense",
    },
    {
      id: "2",
      company: "Apple",
      date: "27 March 2020, at 12:30 PM",
      amount: 2500,
      currency: "$",
      status: "completed",
      type: "income",
    },
    {
      id: "3",
      company: "Stripe",
      date: "26 March 2020, at 13:45 PM",
      amount: 800,
      currency: "$",
      status: "completed",
      type: "income",
    },
    {
      id: "4",
      company: "HubSpot",
      date: "26 March 2020, at 12:30 PM",
      amount: 1700,
      currency: "$",
      status: "completed",
      type: "income",
    },
    {
      id: "5",
      company: "Webflow",
      date: "26 March 2020, at 05:00 AM",
      amount: 0,
      currency: "$",
      status: "pending",
      type: "expense",
    },
    {
      id: "6",
      company: "Microsoft",
      date: "25 March 2020, at 16:30 PM",
      amount: 987,
      currency: "$",
      status: "completed",
      type: "expense",
    },
  ],
}
